### ISSUE TITLE
NO DEJA HACER EL MERGE DE DESARROLLO al MASTER

### ISSUE THREAD

**Issue by Ex0num** [Ex0num/TP_SO_i4_103#6]
Estoy intentando hacer el merge de desarrollo al master y me surgen conflictos. Me dice que no puede ser mergeado automaticamente. ¿Que deberia borrar para poder hacer el merge sin drama?

**Comment by stefanomugetti** [comment]
Borra las lineas (en ambos archivos) para resolver los conflictos.

"======="
">>DESARROLLO"
">>master"

**Comment by Ex0num** [comment]
Muchas gracias. Edité el mensaje porque no me aparecía lo que me habías contestado. Aparecía como header jaja. Listo. Merge hecho.
