### ISSUE TITLE
NO DEJA HACER EL MERGE DE TESTING al MASTER

### ISSUE THREAD

**Issue by Ex0num** [Ex0num/TP_SO_i4_103#9]
En el merge de la rama TESTING a master se detectaron conflictos. ¿Que tendría que modificar para hacer el merge sin drama? Creo que es similar al Issue anterior pero no quiero tocar sin que me confirmen.

**Comment by stefanomugetti** [comment]
Gabriel, fijate de eliminar como antes las
"============"
">>>>>>>master"
"<<<<<TESTING"
y que te quede UN SOLO "background: color",por lo que veo tenes dos. 
Borrale la } y que quede todo adentro como corresponde. 

Con eso debería estar resuelto el conflicto.
